spring:
  datasource:
    url: jdbc:h2:mem:weatherdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

rate-limiter:
  request-limit: 5
  period-milliseconds: 3600000

open-weather-map:
  api-key: b3a46e752946126e2bd590bfcd93eb86
  name-api-url: http://api.openweathermap.org/data/2.5/weather

weather:
  cache-duration-minutes: 15